### ISSUE TITLE
How to define the .npz file in the membership attack?

### ISSUE THREAD

**Issue by Tianlong-Chen** [inspire-group/privacy-vs-robustness#1]

**Comment by lwsong** [comment]
Hi,
The .npz file contains 6 arrays: training and test labels; model predictions on benign training and test data; model predictions on adversarial training and test data.
Here is an example: https://github.com/inspire-group/privacy-vs-robustness/blob/master/PGD-based%20adversarial%20training/CIFAR10/output_performance.ipynb
